### ISSUE TITLE
✨(backend) `/api/v1.0/teams/{team_id}/accesses/me/`

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/people#87]
## Feature Request

For the moment, we don't have a way:
- to know the role of the current user per team
- to know if the current user is the last owner

It would be nice to have the endpoint: 
`/api/v1.0/teams/{team_id}/accesses/me/`

#### Response:
```json
{
  "id": "03fd543f-883e-4d40-b415-a67b3445b685",
  "user": {
    "id": "2a24d537-42e0-47e9-8019-7a8e36e6f7bc",
    "name": null,
    "email": null
   },
  "role": "owner",
  "is_last_owner": true,
  "abilities": {
    "delete": false,
    "get": true,
    "patch": false,
    "put": false,
    "set_role_to": []
  }
}
```

## Purpose

If we are `member` of a team, we don't want to propose the action buttons.

![image](https://github.com/numerique-gouv/people/assets/25994652/a622f979-0629-43cb-870b-31fb164b3da4)

---

If we are the `last_owner` of a team, we don't want to be able to update the role.
![image](https://github.com/numerique-gouv/people/assets/25994652/e2da8a48-d687-4d1a-b4b0-78dd1512c609)

**Comment by lebaudantoine** [comment]
I will read again what abilities return to make sure we need to update this response. Will comment my findings here.

**Comment by lebaudantoine** [comment]
Abilities should provide all required information to do what you meant, for a MVP. Let's jump in a call with @sampaccoud or me to clarify!

**Comment by sampaccoud** [comment]
Yes, abilities give all all this info and it is a bit harder than knowing your role in the team because it also depends on the role of each access. 
For example, if I'm an administrator, I can set a member to "administrator" role but I can not modify the role of an "owner"...

The backend does all these computations for you and gives you all the abilities information for the logged-in user in the `abilities` attribute of each team access.
If "delete" is true, you can display the "delete" item in the three dots menu
If "put"  is true, you can display the "modify the role" item in the three dots menu
When "put" is true, the "set_role_to" attribute will indicate to what new role you are able to update this team access...

I hope it clarifies?

**Comment by AntoLC** [comment]
I still see a problem though, if I am a member, `set_role_to` is init, I guess it should be empty:
![image](https://github.com/numerique-gouv/people/assets/25994652/7609c317-26a1-4c8d-84d3-eae5b2bd0ee1)
